global:
  scrape_interval: 30s
  external_labels:
    monitor: 'docker'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090','cadvisor:8080','nodeexporter:9100'] ## IP Address of the localhost